"""Export the Task 4 report from the database.

    python -m pipeline.report

Writes machine-readable exports into reports/ and a generated Markdown
appendix into docs/. The hand-written narrative lives in docs/DATA_ISSUES.md;
this module produces the exhaustive backing evidence for it, so the two cannot
drift apart - regenerate and the counts update.

Reads from SQLite rather than from the in-memory run, so the report is always a
description of what is actually in the database.
"""
import argparse
import csv
import io
import json
import os
import sys
from collections import Counter, OrderedDict

from . import config
from .load import connect

SEVERITY_RANK = "CASE severity WHEN 'error' THEN 0 WHEN 'warn' THEN 1 ELSE 2 END"

EXPORTS = OrderedDict([
    ("data_issues.csv", """
        SELECT severity, category, source_name, source_row_number, field,
               raw_value, entity, description, action_taken
          FROM data_issues ORDER BY {rank}, category, source_name, source_row_number
     """),
    ("people.csv", """
        SELECT person_id, full_name, email, phone, city, city_region,
               experience_years, ctc_annual_inr, ctc_unit_detected, applied_date,
               applied_date_ambiguous, applied_date_is_future, rate_hourly_inr,
               rate_monthly_inr, rate_basis_raw, gig_status, is_verified,
               projects_completed, skills, sources, source_count, record_count,
               match_methods, match_confidence
          FROM v_people_full ORDER BY person_id
     """),
    ("field_conflicts.csv", """
        SELECT c.person_id, p.full_name, c.field, c.chosen_value, c.chosen_source,
               c.rejected_value, c.rejected_source, c.rule
          FROM field_conflicts c LEFT JOIN people p USING (person_id)
         ORDER BY c.person_id
     """),
    ("merge_review.csv", """
        SELECT review_id, reason, name_key, city, cluster_root, cluster_size,
               score, detail, resolved
          FROM merge_review ORDER BY reason, name_key
     """),
    ("source_records.csv", """
        SELECT source_record_id, source_name, source_row_number, person_id,
               was_used, repairs, raw_json
          FROM source_records ORDER BY source_name, source_row_number
     """),
])


def _write_csv(path, rows, columns):
    with io.open(path, "w", encoding="utf-8", newline="") as fh:
        writer = csv.writer(fh)
        writer.writerow(columns)
        for row in rows:
            writer.writerow(["" if row[c] is None else row[c] for c in columns])


def export(db_path=None, reports_dir=None, docs_dir=None):
    reports_dir = reports_dir or config.REPORTS_DIR
    docs_dir = docs_dir or os.path.join(config.ROOT, "docs")
    for directory in (reports_dir, docs_dir):
        if not os.path.isdir(directory):
            os.makedirs(directory)

    conn = connect(db_path)
    written = []
    try:
        for filename, sql in EXPORTS.items():
            cursor = conn.execute(sql.format(rank=SEVERITY_RANK))
            columns = [d[0] for d in cursor.description]
            rows = cursor.fetchall()
            path = os.path.join(reports_dir, filename)
            _write_csv(path, rows, columns)
            written.append((path, len(rows)))

        issues = [dict(r) for r in conn.execute(
            "SELECT * FROM data_issues ORDER BY %s, category" % SEVERITY_RANK)]
        path = os.path.join(reports_dir, "data_issues.json")
        with io.open(path, "w", encoding="utf-8") as fh:
            fh.write(json.dumps({
                "generated_from": os.path.abspath(db_path or config.DB_PATH),
                "ingest_date": config.INGEST_DATE,
                "totals": dict(Counter(i["severity"] for i in issues)),
                "by_category": dict(Counter(i["category"] for i in issues)),
                "issues": issues,
            }, indent=2, ensure_ascii=False))
        written.append((path, len(issues)))

        appendix = os.path.join(docs_dir, "DATA_ISSUES_APPENDIX.md")
        with io.open(appendix, "w", encoding="utf-8") as fh:
            fh.write(_appendix_markdown(conn))
        written.append((appendix, None))
    finally:
        conn.close()
    return written


# ---------------------------------------------------------------------------

def _md_escape(text):
    return str(text).replace("|", "\\|").replace("\n", " ")


def _appendix_markdown(conn):
    out = []
    w = out.append

    run = conn.execute(
        "SELECT * FROM load_runs ORDER BY run_id DESC LIMIT 1").fetchone()
    totals = Counter(r["severity"] for r in conn.execute("SELECT severity FROM data_issues"))

    w("# Data issues — generated appendix\n")
    w("> Generated by `python -m pipeline.report` from `db/consultbae.db`. "
      "Do not edit by hand — the narrative version is "
      "[DATA_ISSUES.md](DATA_ISSUES.md).\n")
    w("Run %s · ingest date `%s` · %d CSV rows read → %d people · "
      "**%d issues logged** (%d error / %d warn / %d info)\n" % (
          run["run_id"], run["ingest_date"], run["source_rows_read"],
          run["people_created"], run["issues_logged"],
          totals.get("error", 0), totals.get("warn", 0), totals.get("info", 0)))

    w("\n## Every issue class, with counts\n")
    w("| Severity | Category | Field | Count | Files affected |")
    w("| --- | --- | --- | --- | --- |")
    rows = conn.execute("""
        SELECT severity, category, COALESCE(field, '—') AS field, COUNT(*) AS n,
               COUNT(DISTINCT source_name) AS files
          FROM data_issues GROUP BY severity, category, field
         ORDER BY %s, n DESC, category
    """ % SEVERITY_RANK)
    for row in rows:
        w("| %s | `%s` | `%s` | %d | %d |" % (
            row["severity"], row["category"], row["field"], row["n"], row["files"]))

    w("\n## Issues per source file\n")
    w("| File | error | warn | info | total |")
    w("| --- | --- | --- | --- | --- |")
    for row in conn.execute("""
        SELECT COALESCE(source_name, '(whole dataset)') AS src,
               SUM(severity = 'error') AS e, SUM(severity = 'warn') AS w,
               SUM(severity = 'info') AS i, COUNT(*) AS n
          FROM data_issues GROUP BY src ORDER BY n DESC
    """):
        w("| `%s` | %d | %d | %d | %d |" % (
            row["src"], row["e"], row["w"], row["i"], row["n"]))

    w("\n## Every error and warning, in full\n")
    w("These are the %d issues that changed what landed in the database or that "
      "need a human. The %d `info` rows (cosmetic normalisation such as casing "
      "and phone formatting) are in "
      "[`reports/data_issues.csv`](../reports/data_issues.csv).\n" % (
          totals.get("error", 0) + totals.get("warn", 0), totals.get("info", 0)))

    for severity in ("error", "warn"):
        rows = conn.execute(
            "SELECT * FROM data_issues WHERE severity = ? "
            "ORDER BY category, source_name, source_row_number", (severity,)).fetchall()
        if not rows:
            continue
        w("\n### `%s` (%d)\n" % (severity, len(rows)))
        w("| Where | Field | Raw value | Problem | What the pipeline did |")
        w("| --- | --- | --- | --- | --- |")
        for row in rows:
            where = row["source_name"] or "(whole dataset)"
            if row["source_row_number"]:
                where += " row %d" % row["source_row_number"]
            w("| %s | %s | %s | %s | %s |" % (
                _md_escape(where),
                "`%s`" % row["field"] if row["field"] else "—",
                "`%s`" % _md_escape(row["raw_value"]) if row["raw_value"] else "—",
                _md_escape(row["description"]),
                _md_escape(row["action_taken"])))

    w("\n## Field conflicts resolved during merge\n")
    rows = conn.execute("""
        SELECT p.full_name, c.field, c.chosen_value, c.rejected_value, c.rule
          FROM field_conflicts c LEFT JOIN people p USING (person_id)
    """).fetchall()
    if rows:
        w("| Person | Field | Kept | Discarded | Rule |")
        w("| --- | --- | --- | --- | --- |")
        for row in rows:
            w("| %s | `%s` | `%s` | `%s` | %s |" % (
                _md_escape(row["full_name"]), row["field"],
                _md_escape(row["chosen_value"]), _md_escape(row["rejected_value"]),
                _md_escape(row["rule"])))
    else:
        w("_None._")

    w("\n## Merges the pipeline refused to make\n")
    rows = conn.execute("SELECT * FROM merge_review").fetchall()
    if rows:
        w("| Reason | Name | City | Cluster | Rows | Why not merged |")
        w("| --- | --- | --- | --- | --- | --- |")
        for row in rows:
            w("| `%s` | %s | %s | `%s` | %d | %s |" % (
                row["reason"], _md_escape(row["name_key"]), _md_escape(row["city"]),
                _md_escape(row["cluster_root"]), row["cluster_size"],
                _md_escape(row["detail"])))
    else:
        w("_None._")

    w("\n## Row-level outcome per file\n")
    w("| File | Rows in file | Rows loaded | Rows skipped | Rows repaired |")
    w("| --- | --- | --- | --- | --- |")
    for row in conn.execute("""
        SELECT source_name,
               COUNT(*) AS total,
               SUM(was_used) AS used,
               SUM(1 - was_used) AS skipped,
               SUM(repairs IS NOT NULL) AS repaired
          FROM source_records GROUP BY source_name ORDER BY source_name
    """):
        w("| `%s` | %d | %d | %d | %d |" % (
            row["source_name"], row["total"], row["used"], row["skipped"], row["repaired"]))
    w("\n(Fully blank lines and repeated header lines never become rows at all, "
      "so they are counted in the issue tables above rather than here.)\n")

    return "\n".join(out) + "\n"


def main(argv=None):
    parser = argparse.ArgumentParser(description="Export the data-issues report")
    parser.add_argument("--db", dest="db_path", default=None)
    args = parser.parse_args(argv)

    if not os.path.exists(args.db_path or config.DB_PATH):
        print("No database found. Run `python -m pipeline.run` first.")
        return 1
    for path, count in export(db_path=args.db_path):
        rel = os.path.relpath(path, config.ROOT)
        print("  wrote %-42s %s" % (rel, "" if count is None else "%d rows" % count))
    return 0


if __name__ == "__main__":
    sys.exit(main())
